version: '3'

services:
  lavalink:
    container_name: lavalink
    image: fredboat/lavalink:dev
    network_mode: host
    restart: on-failure
    ports:
      - 2333:2333
    volumes:
      - ./lavalink_server/application.yml:/opt/Lavalink/application.yml

  bot:
    container_name: obsidian
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: on-failure

    env_file: 
      - ./.env

    depends_on:
      - lavalink

