name: obsidian_dart
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
dependencies:
  dio: ^4.0.0
  dotenv: ^3.0.0
  http: ^0.13.4
  nyxx: ^2.1.1
  nyxx_extensions: ^2.0.0
  nyxx_interactions: ^2.0.2
  nyxx_lavalink: ^2.0.1
  math_expressions: ^2.2.0
  supabase: ^0.2.7
